package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.matrix
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'EmptyValues'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("EmptyValues")) {
    features {
        remove {
            matrix {
                param("dts_Param", listOf(
                    value("value", label = "label"),
                    value(""),
                    value("onlyValue")
                ))
            }
        }
        add {
            matrix {
                param("dts_Param", listOf(
                    value("value", label = "label"),
                    value("value_main")
                ))
            }
        }
    }
}
